# docker run -d -rm --name mongo -p 27017:27017 -v mongodbdata/data/db mongo

version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672 # to comunicate microservices
      - 15672:15672 # rabittmq dashboard
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
volumes:
  mongodbdata:
  rabbitmqdata:
